"""`CalcJob` implementation running an arbitrary ASE calculator, e.g. a machine-learning interatomic potential.

The calculation generates a small Python script that reconstructs the input structure, instantiates an ASE calculator
from a dynamic import specification, performs the requested task and writes the results to a JSON file. It is designed
as the *engine swap point* for machine-learning potentials: the parsed outputs follow the conventions of the pw.x
stack where physically meaningful (energies in eV, forces in eV/Å, stress in GPa, relaxed structure as a
``StructureData``), so that workflows can compare a DFT engine and an ML engine head-to-head.

The calculator is selected through data, not code, e.g. for a GRACE foundation model::

    calculator = Dict({'module': 'tensorpotential.calculator', 'callable': 'grace_fm', 'args': ['GRACE-1L-OAM']})

and for the dependency-free EMT calculator used in tests::

    calculator = Dict({'module': 'ase.calculators.emt', 'callable': 'EMT'})

The associated ``Code`` is simply a Python interpreter in which ASE (and the calculator package) is installed.

Supported tasks:

- ``energy``: single-point evaluation of the energy, forces and stress.
- ``relax``: geometry optimization with an ASE optimizer, optionally including the cell (via ``FrechetCellFilter``).

Since machine-learning potentials provide no electronic-structure information, calculations and workflows that
require wavefunctions, eigenvalues or charge densities (bands, DOS, dielectric, transport, DFPT) cannot use this
engine; see the documentation for the compatibility matrix.
"""

import json

from aiida import orm
from aiida.common import datastructures
from aiida.orm.nodes.data.base import to_aiida_type

from aiida_quantumespresso.calculations.base import CalcJob

_SCRIPT_TEMPLATE = '''"""Run an ASE calculator task. Generated by aiida-quantumespresso `AseCalculation`."""
import importlib
import json
import traceback

CONFIG = json.loads("""__CONFIG_JSON__""")

results = {'task': CONFIG['task']}

try:
    from ase.io import read, write

    atoms = read(CONFIG['structure_filename'], format='extxyz')

    module = importlib.import_module(CONFIG['calculator']['module'])
    factory = getattr(module, CONFIG['calculator']['callable'])
    atoms.calc = factory(*CONFIG['calculator'].get('args', []), **CONFIG['calculator'].get('kwargs', {}))

    EV_PER_A3_TO_GPA = 160.21766208

    if CONFIG['task'] == 'relax':
        import ase.optimize
        from ase.filters import FrechetCellFilter

        parameters = CONFIG['parameters']
        target = atoms
        if parameters['relax_cell']:
            target = FrechetCellFilter(atoms, hydrostatic_strain=parameters['hydrostatic_strain'])

        optimizer_cls = getattr(ase.optimize, parameters['optimizer'])
        optimizer = optimizer_cls(target, trajectory=None, logfile='-')
        converged = optimizer.run(fmax=parameters['fmax'], steps=parameters['steps'])

        results['converged'] = bool(converged)
        results['n_steps'] = int(optimizer.get_number_of_steps())
        write(CONFIG['output_structure_filename'], atoms, format='extxyz')

    elif CONFIG['task'] == 'phonons':
        from ase.phonons import Phonons

        parameters = CONFIG['parameters']
        phonons = Phonons(
            atoms, atoms.calc, supercell=tuple(parameters['supercell']), delta=parameters['displacement']
        )
        phonons.run()
        phonons.read(acoustic=True)
        phonons.clean()

        path = atoms.cell.bandpath(npoints=parameters['path_npoints'])
        band_structure = phonons.get_band_structure(path)

        EV_TO_THZ = 241.79893
        results['phonon_qpoints'] = path.kpts.tolist()
        results['phonon_path'] = path.path
        results['phonon_special_points'] = {name: kpt.tolist() for name, kpt in path.special_points.items()}
        results['phonon_frequencies'] = (band_structure.energies[0] * EV_TO_THZ).tolist()

    results['energy'] = float(atoms.get_potential_energy())
    results['forces'] = atoms.get_forces().tolist()
    try:
        results['stress'] = (atoms.get_stress(voigt=False) * EV_PER_A3_TO_GPA).tolist()
    except Exception:  # noqa: BLE001 - not every calculator implements stress
        results['stress'] = None
    results['cell'] = atoms.get_cell().tolist()
    results['positions'] = atoms.get_positions().tolist()
    results['symbols'] = atoms.get_chemical_symbols()
except Exception:  # noqa: BLE001 - any failure is reported through the results file for the parser
    results['exception'] = traceback.format_exc()

with open(CONFIG['results_filename'], 'w') as handle:
    json.dump(results, handle, indent=2)
'''


def validate_calculator(value, _):
    """Validate the ``calculator`` input dictionary."""
    if value is None:
        return

    calculator = value.get_dict()

    for key in ('module', 'callable'):
        if not isinstance(calculator.get(key), str) or not calculator.get(key):
            return f'the `calculator` dictionary requires a non-empty string for the `{key}` key.'

    if not isinstance(calculator.get('args', []), list):
        return 'the `calculator.args` key has to be a list.'
    if not isinstance(calculator.get('kwargs', {}), dict):
        return 'the `calculator.kwargs` key has to be a dictionary.'


def validate_task(value, _):
    """Validate the ``task`` input."""
    if value is not None and value.value not in AseCalculation._TASKS:  # noqa: SLF001
        return f'the `task` has to be one of: {", ".join(AseCalculation._TASKS)}.'  # noqa: SLF001


def validate_parameters(value, _):
    """Validate the ``parameters`` input dictionary."""
    if value is None:
        return

    parameters = value.get_dict()
    supported = set(AseCalculation._DEFAULT_RELAX_PARAMETERS) | set(AseCalculation._DEFAULT_PHONONS_PARAMETERS)  # noqa: SLF001
    unknown = set(parameters.keys()) - supported
    if unknown:
        return f'the `parameters` dictionary contains unsupported keys: {", ".join(sorted(unknown))}.'


class AseCalculation(CalcJob):
    """`CalcJob` implementation running an arbitrary ASE calculator, e.g. a machine-learning potential."""

    _TASKS = ('energy', 'relax', 'phonons')

    _SCRIPT_FILENAME = 'aiida_ase_script.py'
    _STRUCTURE_FILENAME = 'structure.xyz'
    _RESULTS_FILENAME = 'results.json'
    _OUTPUT_STRUCTURE_FILENAME = 'output_structure.xyz'

    _DEFAULT_OUTPUT_FILE = 'aiida.out'
    _default_parser = 'quantumespresso.ase'

    # Default parameters of the `relax` task, overridable through the `parameters` input.
    _DEFAULT_RELAX_PARAMETERS = {
        'optimizer': 'BFGS',  # any optimizer class from `ase.optimize`
        'fmax': 0.01,  # eV/Å, force threshold of the optimizer
        'steps': 200,  # maximum number of optimizer steps
        'relax_cell': True,  # relax the cell vectors (via the `FrechetCellFilter`) along with the positions
        'hydrostatic_strain': False,  # constrain the cell relaxation to isotropic scaling
    }

    # Default parameters of the `phonons` task (finite displacements with `ase.phonons.Phonons`).
    _DEFAULT_PHONONS_PARAMETERS = {
        'supercell': [2, 2, 2],  # supercell repetitions for the finite displacements
        'displacement': 0.05,  # Å, finite-displacement amplitude
        'path_npoints': 31,  # number of q-points along the automatic high-symmetry band path
    }

    @classmethod
    def define(cls, spec):
        """Define the process specification."""
        super().define(spec)
        spec.input('metadata.options.output_filename', valid_type=str, default=cls._DEFAULT_OUTPUT_FILE)
        # ASE calculators (and ML potentials in particular) parallelise over threads, not MPI ranks.
        spec.input('metadata.options.withmpi', valid_type=bool, default=False)
        spec.input('metadata.options.parser_name', valid_type=str, default=cls._default_parser)
        spec.input('structure', valid_type=orm.StructureData, help='The input structure.')
        spec.input(
            'calculator',
            valid_type=orm.Dict,
            validator=validate_calculator,
            help='Import specification of the ASE calculator: `module` and `callable` (strings), and optionally '
            '`args` (list) and `kwargs` (dict) passed to the callable.',
        )
        spec.input(
            'task',
            valid_type=orm.Str,
            serializer=to_aiida_type,
            default=lambda: orm.Str('energy'),
            validator=validate_task,
            help="The task to perform: 'energy' (single-point energy/forces/stress), 'relax' (geometry "
            "optimization with an ASE optimizer) or 'phonons' (finite-displacement phonon dispersion along the "
            'automatic high-symmetry q-point path).',
        )
        spec.input(
            'parameters',
            valid_type=orm.Dict,
            required=False,
            validator=validate_parameters,
            help='Parameters of the `relax` task: `optimizer` (class name in `ase.optimize`), `fmax` (eV/Å), '
            '`steps`, `relax_cell` and `hydrostatic_strain`.',
        )

        spec.output(
            'output_parameters',
            valid_type=orm.Dict,
            help='Scalar results: `energy` (eV), `max_force` (eV/Å), `pressure` (GPa), convergence information and '
            'the calculator specification.',
        )
        spec.output('output_forces', valid_type=orm.ArrayData, help='The `forces` (eV/Å) and `stress` (GPa) arrays.')
        spec.output(
            'output_structure',
            valid_type=orm.StructureData,
            required=False,
            help='The relaxed structure (only for the `relax` task).',
        )
        spec.output(
            'output_phonon_bands',
            valid_type=orm.BandsData,
            required=False,
            help='The finite-displacement phonon dispersion in THz (only for the `phonons` task).',
        )
        spec.default_output_node = 'output_parameters'

        spec.exit_code(
            303,
            'ERROR_OUTPUT_RESULTS_MISSING',
            message='The results JSON file was not retrieved.',
        )
        spec.exit_code(
            310,
            'ERROR_OUTPUT_RESULTS_READ',
            message='The results JSON file could not be read or parsed.',
        )
        spec.exit_code(
            320,
            'ERROR_CALCULATOR_FAILED',
            message='The ASE calculator raised an exception: {exception}',
        )
        spec.exit_code(
            500,
            'ERROR_RELAX_NOT_CONVERGED',
            message='The geometry optimization did not converge within the maximum number of steps.',
        )

    @classmethod
    def get_relax_parameters(cls, overrides=None):
        """Return the default parameters of the ``relax`` task, optionally merged with the given overrides."""
        return cls.get_task_parameters('relax', overrides)

    @classmethod
    def get_task_parameters(cls, task, overrides=None):
        """Return the default parameters of the given task, optionally merged with the given overrides."""
        defaults = {
            'energy': {},
            'relax': cls._DEFAULT_RELAX_PARAMETERS,
            'phonons': cls._DEFAULT_PHONONS_PARAMETERS,
        }
        # Only the keys of the task at hand are forwarded, so that a single `parameters` dictionary carrying the
        # settings of several tasks can be reused across calculations.
        parameters = dict(defaults[task])
        parameters.update({key: value for key, value in (overrides or {}).items() if key in parameters})
        return parameters

    def prepare_for_submission(self, folder):
        """Write the structure, the generated runner script, and return the calculation info.

        :param folder: a sandbox folder to temporarily write files on disk.
        :return: :class:`~aiida.common.datastructures.CalcInfo` instance.
        """
        from ase.io import write

        task = self.inputs.task.value

        config = {
            'task': task,
            'calculator': self.inputs.calculator.get_dict(),
            'structure_filename': self._STRUCTURE_FILENAME,
            'results_filename': self._RESULTS_FILENAME,
            'output_structure_filename': self._OUTPUT_STRUCTURE_FILENAME,
            'parameters': self.get_task_parameters(
                task, self.inputs.parameters.get_dict() if 'parameters' in self.inputs else None
            ),
        }

        with folder.open(self._STRUCTURE_FILENAME, 'w') as handle:
            write(handle, self.inputs.structure.get_ase(), format='extxyz')

        with folder.open(self._SCRIPT_FILENAME, 'w') as handle:
            handle.write(_SCRIPT_TEMPLATE.replace('__CONFIG_JSON__', json.dumps(config, sort_keys=True)))

        codeinfo = datastructures.CodeInfo()
        codeinfo.code_uuid = self.inputs.code.uuid
        codeinfo.cmdline_params = [self._SCRIPT_FILENAME]
        codeinfo.stdout_name = self.metadata.options.output_filename

        calcinfo = datastructures.CalcInfo()
        calcinfo.uuid = str(self.uuid)
        calcinfo.codes_info = [codeinfo]
        calcinfo.retrieve_list = [
            self.metadata.options.output_filename,
            self._RESULTS_FILENAME,
            self._OUTPUT_STRUCTURE_FILENAME,
        ]

        return calcinfo
