"""Workchain to compute the phonon band structure of a structure with Quantum ESPRESSO.

This requires four computations:

- SCF (pw.x), to generate the ground-state charge density.
- PH (ph.x), to compute the dynamical matrices on a uniform q-point grid via density-functional perturbation theory.
- Q2R (q2r.x), to Fourier-transform the dynamical matrices into real-space interatomic force constants.
- MATDYN (matdyn.x), to interpolate the force constants along a high-symmetry q-point path and obtain the phonon
  dispersion.

The high-symmetry q-point path is determined automatically with SeeK-path, unless an explicit path is provided through
the ``bands_kpoints`` input. Note that SeeK-path can modify the structure to the standardized primitive cell, in which
case the normalized structure is used for all calculations and returned as the ``primitive_structure`` output. The
SCF/PH/Q2R scaffolding is inherited from the
:class:`~aiida_quantumespresso.workflows.phonon.PhononWorkChain` base class.
"""

from aiida import orm
from aiida.engine import if_
from aiida.orm.nodes.data.base import to_aiida_type

from aiida_quantumespresso.calculations.functions.seekpath_structure_analysis import seekpath_structure_analysis

from .phonon import MatdynBaseWorkChain, PhBaseWorkChain, PhononWorkChain, Q2rBaseWorkChain


def validate_inputs(value, _):
    """Validate the top level namespace."""
    if all(key in value for key in ['bands_kpoints', 'bands_kpoints_distance']):
        return 'Cannot specify both `bands_kpoints` and `bands_kpoints_distance`.'


class PhononBandsWorkChain(PhononWorkChain):
    """A WorkChain to compute the phonon band structure of a structure, using Quantum ESPRESSO."""

    @classmethod
    def define(cls, spec):
        """Define the process specification."""
        super().define(spec)
        spec.input(
            'bands_kpoints',
            valid_type=orm.KpointsData,
            required=False,
            help='Explicit q-points to use for the phonon dispersion. Specify either this or '
            '`bands_kpoints_distance`. If neither is specified, the path is generated by SeeK-path with its default '
            'reference distance.',
        )
        spec.input(
            'bands_kpoints_distance',
            valid_type=orm.Float,
            serializer=to_aiida_type,
            required=False,
            help='Minimum distance between q-points of the dispersion path, used by SeeK-path. Specify either this '
            'or `bands_kpoints`.',
        )
        spec.inputs.validator = validate_inputs

        spec.outline(
            cls.setup,
            if_(cls.should_run_seekpath)(
                cls.run_seekpath,
            ),
            cls.run_scf,
            cls.inspect_scf,
            cls.run_ph,
            cls.inspect_ph,
            cls.run_q2r,
            cls.inspect_q2r,
            cls.run_matdyn,
            cls.inspect_matdyn,
            cls.results,
        )

        spec.output(
            'primitive_structure',
            valid_type=orm.StructureData,
            required=False,
            help='The normalized and primitivized structure for which the phonons are computed.',
        )
        spec.output(
            'seekpath_parameters',
            valid_type=orm.Dict,
            required=False,
            help='The parameters used in the SeeK-path call to normalize the input or relaxed structure.',
        )
        spec.expose_outputs(Q2rBaseWorkChain, namespace='q2r')

    @classmethod
    def get_protocol_filepath(cls):
        """Return ``pathlib.Path`` to the ``.yaml`` file that defines the protocols."""
        from importlib_resources import files

        from . import protocols

        return files(protocols) / 'phonon_bands.yaml'

    @classmethod
    def get_builder_from_protocol(
        cls, pw_code, ph_code, q2r_code, matdyn_code, structure, protocol=None, overrides=None, options=None, **kwargs
    ):
        """Return a builder prepopulated with inputs selected according to the chosen protocol.

        :param pw_code: the ``Code`` instance configured for the ``quantumespresso.pw`` plugin.
        :param ph_code: the ``Code`` instance configured for the ``quantumespresso.ph`` plugin.
        :param q2r_code: the ``Code`` instance configured for the ``quantumespresso.q2r`` plugin.
        :param matdyn_code: the ``Code`` instance configured for the ``quantumespresso.matdyn`` plugin.
        :param structure: the ``StructureData`` instance to use.
        :param protocol: protocol to use, if not specified, the default will be used.
        :param overrides: optional dictionary of inputs to override the defaults of the protocol.
        :param options: A dictionary of options that will be recursively set for the ``metadata.options`` input of all
            the ``CalcJobs`` that are nested in this work chain.
        :param kwargs: additional keyword arguments that will be passed to the ``get_builder_from_protocol`` of all the
            sub processes that are called by this workchain.
        :return: a process builder instance with all inputs defined ready for launch.
        """
        from aiida_quantumespresso.utils.ase import as_structure_data

        inputs = cls.get_protocol_inputs(protocol, overrides)
        structure = as_structure_data(structure)

        builder = cls.construct_phonon_builder(
            pw_code, ph_code, q2r_code, matdyn_code, structure, protocol, inputs, options=options, **kwargs
        )
        if 'bands_kpoints_distance' in inputs:
            builder.bands_kpoints_distance = orm.Float(inputs['bands_kpoints_distance'])

        return builder

    def setup(self):
        """Initialize context variables that are used during the logical flow of the workchain."""
        super().setup()
        self.ctx.bands_kpoints = self.inputs.get('bands_kpoints', None)

    def should_run_seekpath(self):
        """Seekpath should only be run if the `bands_kpoints` input is not specified."""
        return 'bands_kpoints' not in self.inputs

    def run_seekpath(self):
        """Run the structure through SeeK-path to get the normalized structure and path along high-symmetry q-points.

        This is only called if the `bands_kpoints` input was not specified.
        """
        inputs = {'metadata': {'call_link_label': 'seekpath'}}
        if 'bands_kpoints_distance' in self.inputs:
            inputs['reference_distance'] = self.inputs.bands_kpoints_distance
        result = seekpath_structure_analysis(self.ctx.current_structure, **inputs)
        self.ctx.current_structure = result['primitive_structure']
        self.ctx.bands_kpoints = result['explicit_kpoints']

        self.out('primitive_structure', result['primitive_structure'])
        self.out('seekpath_parameters', result['parameters'])

    def run_matdyn(self):
        """Run a MATDYN calculation, to interpolate the force constants along the high-symmetry q-point path."""
        return self.submit_matdyn(self.ctx.bands_kpoints)

    def results(self):
        """Attach the desired output nodes directly as outputs of the workchain."""
        self.report('workchain successfully completed')

        self.out_many(self.exposed_outputs(self.ctx.workchain_ph, PhBaseWorkChain, namespace='ph'))
        self.out_many(self.exposed_outputs(self.ctx.workchain_q2r, Q2rBaseWorkChain, namespace='q2r'))
        self.out_many(self.exposed_outputs(self.ctx.workchain_matdyn, MatdynBaseWorkChain, namespace='matdyn'))
